Fix some small bugs in misc pattern file reading
-only splits on tabs now, per help messages of collate.py
 (so this works with spaces in cluster types, etc)
-fixed an undefined reference to an error message